name: Auto Deploy to Ubuntu VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Restore dependencies and build
        run: |
          cd ~/Desktop/UserService/UserService
          git pull origin master
          dotnet restore
          dotnet build
          # Restart the service
          sudo systemctl restart userservice.service
