name: Auto Deploy to Ubuntu VM

on:
  push:
    branches:
      - master-sdasd

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Pull the latest changes from the master branch
        run: |
          cd ~/Desktop/UserService/UserService
          git pull origin master

      - name: Stop the UserService service
        run: |
          sudo systemctl stop userservice.service

      - name: Restore dependencies and build the project
        run: |
          dotnet restore
          dotnet build

      - name: Restart the UserService service
        run: |
          sudo systemctl restart userservice.service

      - name: Mark build and deployment as completed
        run: echo "Build and deployment completed successfully!"
