name: UserService

on:
  push:
    branches:
      - main
      - master

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:  
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run app
        run: dotnet run --project UserService/UserService.csproj

