name: Auto Deploy to Ubuntu VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Delete UserService folder and clone the repository
        run: |
          rm -rf ~/Desktop/UserService
          git clone https://github.com/john-andeyyy/UserService.git ~/Desktop/UserService

      - name: (Re)create systemd service file
        run: |
            sudo bash -c 'cat <<EOF > /etc/systemd/system/userservice.service
            [Unit]
            Description=User Service .NET App
            After=network.target

            [Service]
            WorkingDirectory=/home/vboxuser/Desktop/UserService
            xecStart=/usr/bin/dotnet /home/vboxuser/Desktop/UserService/UserService/bin/Debug/net6.0/UserService.dll
            Restart=always
            RestartSec=5
            KillSignal=SIGINT
            SyslogIdentifier=userservice
            User=vboxuser
            Environment=ASPNETCORE_ENVIRONMENT=Production
            Environment=JWT_SECRET_KEY=64A63153-11C1-4919-9133-EFAF99A9B456
            Environment=JWT_ISSUER=https://localhost:5001
            Environment=JWT_AUDIENCE=https://localhost:5001
            Environment=DB_HOST=localhost
            Environment=DB_NAME=UserService
            Environment=DB_USER=root
            Environment=DB_PASS=Andrei_123!
            Environment=EXPIRATION_SECONDS=3600
            Environment=SIGNING_KEY=Andrei

            [Install]
            WantedBy=multi-user.target
            EOF'

            sudo systemctl daemon-reload
            sudo systemctl enable userservice
            sudo systemctl start userservice


      - name: Stop the UserService service (if running)
        run: |
          sudo systemctl stop userservice.service || true  # Stop if already running

      - name: Restore dependencies and build the project
        run: |
          cd ~/Desktop/UserService/UserService
          dotnet restore
          dotnet build

      - name: Restart the UserService service
        run: |
          sudo systemctl restart userservice.service

      - name: Mark build and deployment as completed
        run: echo "✅ Build and deployment completed successfully!"
