name: Test Self-Hosted Runner

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Say hello from Ubuntu VM
        run: echo "Hello from my Ubuntu VM self-hosted runner!"
