name: Deploy to Ubuntu VM

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Ubuntu
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          debug: true
          script: |
            # Navigate to your project directory
            cd /home/vboxuser/Desktop/UserService && \
            # Pull latest changes from the repository
            git pull origin main && \
            # Clean, build, and run the .NET application
            dotnet clean && \
            dotnet build --configuration Release && \
            dotnet run
