name: Deploy to EC2

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}       
          username:  ${{ secrets.EC2_USERNAME }}     
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }} 
          port: 22
          timeout: 30s
          debug: true
          script: |
            # Navigate to your project directory
            cd /home/ubuntu/Desktop/UserService && \
            # Pull latest changes from the repository
            git pull origin main && \

            # Clean, build, and run the .NET application
            dotnet clean && \
            dotnet build --configuration Release && \
            dotnet run
