name: Auto Deploy to Ubuntu VM WITH TPP

on:
  push:
    branches:
      - WITH-TPP

jobs:
  deploy-with-tpp-tpp:
    runs-on: self-hosted

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Delete old UserService folder and clone the repository
        run: |
          rm -rf /home/vboxuser/Desktop/${{ secrets.SERVICE_NAME }}
          git clone --branch WITH-TPP https://github.com/john-andeyyy/UserService.git /home/vboxuser/Desktop/${{ secrets.SERVICE_NAME }}

      - name: Delete old systemd service file (if exists)
        run: |
          sudo rm -f /etc/systemd/system/${{ secrets.SERVICE_NAME }}.service

      - name: (Re)create systemd service file
        run: |
            sudo bash -c 'cat <<EOF > /etc/systemd/system/${{ secrets.SERVICE_NAME }}.service
            [Unit]
            Description=User Service .NET App
            After=network.target

            [Service]
            WorkingDirectory=/home/vboxuser/Desktop/${{ secrets.SERVICE_NAME }}
            ExecStart=/usr/bin/dotnet /home/vboxuser/Desktop/UserService/UserService/bin/Debug/net6.0/UserService.dll
            Restart=always
            RestartSec=5
            KillSignal=SIGINT
            SyslogIdentifier=${{ secrets.SERVICE_NAME }}
            User=vboxuser
            Environment=ASPNETCORE_ENVIRONMENT=Development
            Environment=HOST=${{ secrets.HOST }}
            Environment=PORT=${{ secrets.PORT }}
            Environment=DB_PORT=3306
            Environment=DB_HOST=localhost
            Environment=DB_NAME=${{ secrets.DB_NAME }}
            Environment=DB_USER=${{ secrets.DB_USER }}
            Environment=DB_PASS=${{ secrets.DB_PASS }}
            Environment=EXPIRATION_SECONDS=3600
            Environment=SIGNING_KEY=${{ secrets.SIGNING_KEY }}
            Environment=JWT_ISSUER=https://localhost:5001
            Environment=JWT_AUDIENCE=https://localhost:5001
            Environment=JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}

            # TPP CONFIG
            Environment=TPP_URL=${{ secrets.TPP_URL }}
            Environment=TPP_Username=${{ secrets.TPP_Username }}
            Environment=TPP_Password=${{ secrets.TPP_Password }}

            [Install]
            WantedBy=multi-user.target
            EOF'

            sudo systemctl daemon-reload
            sudo systemctl enable /etc/systemd/system/${{ secrets.SERVICE_NAME }}.service
            sudo systemctl start /etc/systemd/system/${{ secrets.SERVICE_NAME }}.service

      - name: Stop the UserService service (if running)
        run: |
          sudo systemctl stop ${ secrets.SERVICE_NAME }.service || true  # Stop if already running

      - name: Restore dependencies and build the project
        run: |
          cd /home/vboxuser/Desktop/${{ secrets.SERVICE_NAME }}/UserService
          dotnet restore
          dotnet build

      - name: Restart the UserService service
        run: |
          sudo systemctl restart ${ secrets.SERVICE_NAME }.service

      - name: Mark build and deployment as completed
        run: echo " Build and deployment completed successfully!"
